# -*- coding: utf-8 -*-
"""
===============================================================================
PROJECT
    Pacific Warm Pool (PWP) Scientific Analysis Pipeline

PROGRAM
    06_quality_control_and_diagnostics.py

VERSION
    3.1.0

PURPOSE
    Perform comprehensive structural, temporal, statistical, and physical
    quality control on the daily PWP centroid and area series generated by
    05_calculate_pwp_centroid.py.

THRESHOLD MODES
    Single-threshold mode:
        RUN_ALL_THRESHOLDS = False

        The program processes only PWP_SST_THRESHOLD_C.

    Threshold-sensitivity mode:
        RUN_ALL_THRESHOLDS = True

        The program processes the approved thresholds sequentially:

            28.0 °C
            28.5 °C
            29.0 °C

INPUT FOR EACH THRESHOLD
    Centroid series:
        data/processed/<threshold>/centroid/
            pwp_centroid_series.csv

OUTPUT FOR EACH THRESHOLD
    Quality-controlled series:
        data/processed/<threshold>/quality_control/
            pwp_centroid_series_qc.csv

    Tables:
        outputs/tables/<threshold>/quality_control/

    Figures:
        outputs/figures/<threshold>/quality_control/

    Reports:
        outputs/reports/<threshold>/quality_control/
            pwp_quality_control_report.txt

PATH POLICY
    All paths are obtained from the central configuration:

        get_threshold_paths(threshold).centroid
        get_threshold_paths(threshold).quality_control

    The program does not construct threshold-root directories independently.

CROSS-THRESHOLD OUTPUTS
    When more than one threshold is processed:

        outputs/tables/threshold_comparison/quality_control/
            pwp_qc_threshold_comparison_summary.csv

        outputs/figures/threshold_comparison/quality_control/
            pwp_qc_threshold_comparison.png

        outputs/reports/threshold_comparison/quality_control/
            pwp_qc_threshold_comparison_report.txt

QUALITY-CONTROL PHILOSOPHY
    No observation is automatically deleted, replaced, or interpolated.

    All records are retained and diagnostic flags are added transparently.
    Any later exclusion must therefore be explicit, scientifically justified,
    and reproducible.

DIAGNOSTICS
    1. Required columns and numeric conversion.
    2. Date parsing, sorting, duplicate dates, and missing calendar days.
    3. Original processing flags.
    4. Coordinate, area, SST, and coverage plausibility.
    5. Daily longitude, latitude, area, SST, and great-circle displacement.
    6. Rolling robust anomaly detection using median and MAD.
    7. Suspicious constant-value sequences.
    8. Composite PASS, CHECK, and FAIL classification.
    9. Descriptive statistics, correlations, and annual summaries.
   10. Publication-standard diagnostic figures.

ROBUST ANOMALY METHOD
    For variable x(t), centred rolling median and rolling MAD are calculated:

        MAD = median(|x - median(x)|)

        z_robust = 0.67448975 * (x - rolling_median) / rolling_MAD

    Values exceeding ROBUST_Z_THRESHOLD are flagged for inspection.

FIGURE CONVENTIONS
    - Temporal limits match the observed series exactly.
    - Major ticks occur every three years.
    - Ticks are anchored in 1982.
    - In multi-panel figures, date labels appear only on the bottom panel.
    - Panel labels use A), B), C), ...
    - Legends are transparent.

DIRECTORY POLICY
    The directory hierarchy must already exist. Run:

        00_create_project_structure.py

    before this program.

DEPENDENCIES
    numpy
    pandas
    matplotlib

PYTHON
    Python 3.10+

AUTHOR
    Fabio Vieira Machado
===============================================================================
"""

from __future__ import annotations

import hashlib
import json
import sys
import warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# =============================================================================
# PROJECT ROOT AND CENTRAL CONFIGURATION
# =============================================================================

SCRIPT_FILE = Path(__file__).resolve()
ROOT = SCRIPT_FILE.parents[1]

if str(ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(ROOT),
    )

from config.config import (  # noqa: E402
    EARTH_RADIUS_KM,
    FIGURE_DPI,
    GRID_ALPHA,
    GRID_LINESTYLE,
    GRID_LINEWIDTH,
    PANEL_LABEL_FONT_SIZE,
    PANEL_LABEL_FONT_WEIGHT,
    PANEL_LABEL_X,
    PANEL_LABEL_Y,
    PROJECT_DIR,
    PWP_ALLOWED_THRESHOLDS_C,
    RUN_ALL_THRESHOLDS,
    SAVE_BBOX,
    SAVE_PAD_INCHES,
    SAVE_TRANSPARENT,
    THRESHOLD_COMPARISON_FIGURE_DIR,
    THRESHOLD_COMPARISON_REPORT_DIR,
    THRESHOLD_COMPARISON_TABLE_DIR,
    TIME_AXIS_LABEL,
    YEAR_TICK_ANCHOR,
    YEAR_TICK_INTERVAL,
    get_threshold_paths,
    normalize_threshold,
    threshold_folder_name,
    thresholds_to_run,
    validate_project_configuration,
)


# =============================================================================
# PROGRAM CONFIGURATION
# =============================================================================

PROGRAM_NAME = "PACIFIC WARM POOL TIME-SERIES QUALITY CONTROL"
PROGRAM_VERSION = "3.1.0"

# These module variables are assigned for each threshold before processing.
INPUT_CSV = Path()
OUTPUT_QC_CSV = Path()

TABLE_DIR = Path()
FIGURE_DIR = Path()
REPORT_DIR = Path()

SUMMARY_TABLE = Path()
FLAG_COUNT_TABLE = Path()
MISSING_DATES_TABLE = Path()
SUSPECT_RECORDS_TABLE = Path()
DESCRIPTIVE_TABLE = Path()
CORRELATION_TABLE = Path()
ANNUAL_SUMMARY_TABLE = Path()

REPORT_FILE = Path()

FIGURE_DAILY_SERIES = Path()
FIGURE_DAILY_CHANGES = Path()
FIGURE_DISTRIBUTIONS = Path()
FIGURE_COVERAGE_FLAGS = Path()
FIGURE_ANNUAL_SUMMARY = Path()

ACTIVE_THRESHOLD_C = np.nan
ACTIVE_THRESHOLD_FOLDER = ""

COMPARISON_TABLE_DIR = (
    THRESHOLD_COMPARISON_TABLE_DIR
    / "quality_control"
)

COMPARISON_FIGURE_DIR = (
    THRESHOLD_COMPARISON_FIGURE_DIR
    / "quality_control"
)

COMPARISON_REPORT_DIR = (
    THRESHOLD_COMPARISON_REPORT_DIR
    / "quality_control"
)

COMPARISON_SUMMARY_TABLE = (
    COMPARISON_TABLE_DIR
    / "pwp_qc_threshold_comparison_summary.csv"
)

COMPARISON_FIGURE = (
    COMPARISON_FIGURE_DIR
    / "pwp_qc_threshold_comparison.png"
)

COMPARISON_REPORT = (
    COMPARISON_REPORT_DIR
    / "pwp_qc_threshold_comparison_report.txt"
)


class ThresholdContext:
    """Threshold-specific input, output, and analysis paths."""

    def __init__(
        self,
        threshold_c: float,
    ) -> None:
        self.threshold_c = normalize_threshold(
            threshold_c
        )

        self.paths = get_threshold_paths(
            self.threshold_c
        )

        self.folder_name = (
            self.paths.folder_name
        )

        self.centroid_paths = (
            self.paths.centroid
        )

        self.quality_control_paths = (
            self.paths.quality_control
        )

        self.input_csv = (
            self.centroid_paths.processed_dir
            / "pwp_centroid_series.csv"
        )

        self.output_qc_csv = (
            self.quality_control_paths.processed_dir
            / "pwp_centroid_series_qc.csv"
        )

        self.table_dir = (
            self.quality_control_paths.table_dir
        )

        self.figure_dir = (
            self.quality_control_paths.figure_dir
        )

        self.report_dir = (
            self.quality_control_paths.report_dir
        )


def selected_threshold_contexts() -> tuple[
    ThresholdContext,
    ...,
]:
    """Return the configured threshold contexts in execution order."""

    return tuple(
        ThresholdContext(
            threshold_c
        )
        for threshold_c in thresholds_to_run()
    )


def activate_context(
    context: ThresholdContext,
) -> None:
    """Assign threshold-specific paths used by the analysis functions."""

    global INPUT_CSV
    global OUTPUT_QC_CSV
    global TABLE_DIR
    global FIGURE_DIR
    global REPORT_DIR
    global SUMMARY_TABLE
    global FLAG_COUNT_TABLE
    global MISSING_DATES_TABLE
    global SUSPECT_RECORDS_TABLE
    global DESCRIPTIVE_TABLE
    global CORRELATION_TABLE
    global ANNUAL_SUMMARY_TABLE
    global REPORT_FILE
    global FIGURE_DAILY_SERIES
    global FIGURE_DAILY_CHANGES
    global FIGURE_DISTRIBUTIONS
    global FIGURE_COVERAGE_FLAGS
    global FIGURE_ANNUAL_SUMMARY
    global ACTIVE_THRESHOLD_C
    global ACTIVE_THRESHOLD_FOLDER

    ACTIVE_THRESHOLD_C = (
        context.threshold_c
    )

    ACTIVE_THRESHOLD_FOLDER = (
        context.folder_name
    )

    INPUT_CSV = context.input_csv
    OUTPUT_QC_CSV = context.output_qc_csv

    TABLE_DIR = context.table_dir
    FIGURE_DIR = context.figure_dir
    REPORT_DIR = context.report_dir

    SUMMARY_TABLE = (
        TABLE_DIR
        / "pwp_qc_summary.csv"
    )

    FLAG_COUNT_TABLE = (
        TABLE_DIR
        / "pwp_qc_flag_counts.csv"
    )

    MISSING_DATES_TABLE = (
        TABLE_DIR
        / "pwp_qc_missing_dates.csv"
    )

    SUSPECT_RECORDS_TABLE = (
        TABLE_DIR
        / "pwp_qc_suspect_records.csv"
    )

    DESCRIPTIVE_TABLE = (
        TABLE_DIR
        / "pwp_qc_descriptive_statistics.csv"
    )

    CORRELATION_TABLE = (
        TABLE_DIR
        / "pwp_qc_correlations.csv"
    )

    ANNUAL_SUMMARY_TABLE = (
        TABLE_DIR
        / "pwp_qc_annual_summary.csv"
    )

    REPORT_FILE = (
        REPORT_DIR
        / "pwp_quality_control_report.txt"
    )

    FIGURE_DAILY_SERIES = (
        FIGURE_DIR
        / "01_pwp_daily_series_qc.png"
    )

    FIGURE_DAILY_CHANGES = (
        FIGURE_DIR
        / "02_pwp_daily_changes_qc.png"
    )

    FIGURE_DISTRIBUTIONS = (
        FIGURE_DIR
        / "03_pwp_distributions_qc.png"
    )

    FIGURE_COVERAGE_FLAGS = (
        FIGURE_DIR
        / "04_pwp_coverage_and_flags_qc.png"
    )

    FIGURE_ANNUAL_SUMMARY = (
        FIGURE_DIR
        / "05_pwp_annual_summary_qc.png"
    )


def validate_configuration_and_directories(
    contexts: tuple[
        ThresholdContext,
        ...,
    ],
) -> None:
    """Validate configuration, inputs, and pre-created directories."""

    validate_project_configuration()

    if Path(
        PROJECT_DIR
    ).resolve() != ROOT.resolve():
        raise ValueError(
            "Project-root mismatch.\n"
            f"Script-derived root : {ROOT}\n"
            f"Configured root     : {PROJECT_DIR}"
        )

    if not contexts:
        raise ValueError(
            "No thresholds were selected."
        )

    for context in contexts:
        configured_paths = get_threshold_paths(
            context.threshold_c
        )

        configured_centroid = (
            configured_paths.centroid
        )

        configured_qc = (
            configured_paths.quality_control
        )

        if (
            context.input_csv.parent.resolve()
            != configured_centroid.processed_dir.resolve()
        ):
            raise ValueError(
                "Program 06 input is outside the configured centroid "
                "processed-data directory.\n"
                f"Configured : {configured_centroid.processed_dir}\n"
                f"Selected   : {context.input_csv.parent}"
            )

        if (
            context.output_qc_csv.parent.resolve()
            != configured_qc.processed_dir.resolve()
        ):
            raise ValueError(
                "Program 06 output is outside the configured quality-control "
                "processed-data directory.\n"
                f"Configured : {configured_qc.processed_dir}\n"
                f"Selected   : {context.output_qc_csv.parent}"
            )

        directory_pairs = (
            (
                context.table_dir,
                configured_qc.table_dir,
                "table",
            ),
            (
                context.figure_dir,
                configured_qc.figure_dir,
                "figure",
            ),
            (
                context.report_dir,
                configured_qc.report_dir,
                "report",
            ),
        )

        for selected_directory, configured_directory, label in directory_pairs:
            if (
                selected_directory.resolve()
                != configured_directory.resolve()
            ):
                raise ValueError(
                    f"Program 06 {label} directory differs from the central "
                    "quality-control configuration.\n"
                    f"Configured : {configured_directory}\n"
                    f"Selected   : {selected_directory}"
                )

    required_directories: list[
        Path
    ] = []

    for context in contexts:
        required_directories.extend(
            [
                context.output_qc_csv.parent,
                context.table_dir,
                context.figure_dir,
                context.report_dir,
            ]
        )

    if len(
        contexts
    ) > 1:
        required_directories.extend(
            [
                COMPARISON_TABLE_DIR,
                COMPARISON_FIGURE_DIR,
                COMPARISON_REPORT_DIR,
            ]
        )

    missing_directories = sorted(
        {
            directory
            for directory in required_directories
            if not directory.is_dir()
        },
        key=str,
    )

    if missing_directories:
        raise FileNotFoundError(
            "Required output directories are missing. "
            "Run 00_create_project_structure.py first:\n"
            + "\n".join(
                f"  - {directory}"
                for directory in missing_directories
            )
        )


# =============================================================================
# REQUIRED VARIABLES
# =============================================================================

REQUIRED_COLUMNS = (
    "date",
    "lon_360",
    "lon_180",
    "lat",
    "area_km2",
    "pwp_cell_count",
    "valid_ocean_cell_count",
    "mask_cell_count",
    "ocean_data_coverage_pct",
    "mean_pwp_sst_c",
    "max_pwp_sst_c",
    "area_weighted_sst_std_c",
    "threshold_c",
    "threshold_source",
    "threshold_fallback_used",
    "centroid_resultant_length",
    "centroid_angular_dispersion_deg",
    "quality_flag",
    "source_file",
)

NUMERIC_COLUMNS = (
    "lon_360",
    "lon_180",
    "lat",
    "area_km2",
    "pwp_cell_count",
    "valid_ocean_cell_count",
    "mask_cell_count",
    "ocean_data_coverage_pct",
    "mean_pwp_sst_c",
    "max_pwp_sst_c",
    "area_weighted_sst_std_c",
    "threshold_c",
    "centroid_resultant_length",
    "centroid_angular_dispersion_deg",
)


# =============================================================================
# SCIENTIFIC AND QC CONFIGURATION
# =============================================================================

#MINIMUM_EXPECTED_COVERAGE_PCT = 99.0
# A máscara legada contém algumas células costeiras que permanecem
# ausentes na OISST. O limite operacional deve detectar perdas anormais
# adicionais, e não penalizar a incompatibilidade estrutural das máscaras.
MINIMUM_EXPECTED_COVERAGE_PCT = 98.0

PHYSICAL_LAT_MIN = -90.0
PHYSICAL_LAT_MAX = 90.0

PHYSICAL_LON_360_MIN = 0.0
PHYSICAL_LON_360_MAX = 360.0

PHYSICAL_AREA_MIN_KM2 = 0.0
EARTH_SURFACE_AREA_KM2 = 4.0 * np.pi * EARTH_RADIUS_KM**2

PHYSICAL_SST_MIN_C = -3.0
PHYSICAL_SST_MAX_C = 45.0

# Rolling robust anomaly detection.
ROLLING_WINDOW_DAYS = 365
ROLLING_MIN_PERIODS = 180
ROBUST_Z_THRESHOLD = 6.0

# Daily-change thresholds used as conservative diagnostic limits.
# These values flag records for inspection; they do not prove invalidity.
MAX_DAILY_LON_CHANGE_DEG = 10.0
MAX_DAILY_LAT_CHANGE_DEG = 5.0
MAX_DAILY_CENTROID_DISTANCE_KM = 1500.0
MAX_DAILY_AREA_FRACTION_CHANGE = 0.50
MAX_DAILY_MEAN_SST_CHANGE_C = 2.0

# Constant sequences may indicate repeated fields or data-processing problems.
CONSTANT_SEQUENCE_MIN_DAYS = 7
CONSTANT_TOLERANCE = 1.0e-10



# =============================================================================
# BASIC UTILITIES
# =============================================================================

def print_header(title: str) -> None:
    """Print a standardized terminal header."""

    print("=" * 78)
    print(title)
    print("=" * 78)


def print_section(title: str) -> None:
    """Print a standardized terminal section."""

    print()
    print(title)
    print("-" * 78)


def calculate_sha256(file_path: Path) -> str:
    """Calculate the SHA-256 checksum of a file."""

    digest = hashlib.sha256()

    with file_path.open("rb") as file:
        for block in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(block)

    return digest.hexdigest()


def ensure_output_directories() -> None:
    """
    Validate the active threshold output directories.

    The complete hierarchy is created by 00_create_project_structure.py.
    """

    required = (
        OUTPUT_QC_CSV.parent,
        TABLE_DIR,
        FIGURE_DIR,
        REPORT_DIR,
    )

    missing = [
        directory
        for directory in required
        if not directory.is_dir()
    ]

    if missing:
        raise FileNotFoundError(
            "Active output directories are missing. "
            "Run 00_create_project_structure.py first:\n"
            + "\n".join(
                f"  - {directory}"
                for directory in missing
            )
        )


# =============================================================================
# DATA LOADING AND STRUCTURAL VALIDATION
# =============================================================================

def load_input_series() -> pd.DataFrame:
    """Load and validate one threshold-specific daily PWP series."""

    if not INPUT_CSV.is_file():
        raise FileNotFoundError(
            "Input time-series file not found:\n"
            f"{INPUT_CSV}\n\n"
            "Run 05_calculate_pwp_centroid.py for this threshold first."
        )

    dataframe = pd.read_csv(
        INPUT_CSV,
        low_memory=False,
    )

    missing_columns = [
        column
        for column in REQUIRED_COLUMNS
        if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(
            "The input CSV is missing required column(s):\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_columns
            )
        )

    dataframe = dataframe.copy()

    dataframe[
        "date"
    ] = pd.to_datetime(
        dataframe[
            "date"
        ],
        errors="coerce",
    )

    invalid_date_count = int(
        dataframe[
            "date"
        ].isna().sum()
    )

    if invalid_date_count > 0:
        raise ValueError(
            f"The input contains {invalid_date_count:,} invalid dates."
        )

    for column in NUMERIC_COLUMNS:
        dataframe[
            column
        ] = pd.to_numeric(
            dataframe[
                column
            ],
            errors="coerce",
        )

    for column in (
        "quality_flag",
        "threshold_source",
        "source_file",
    ):
        dataframe[
            column
        ] = (
            dataframe[
                column
            ]
            .astype(
                "string"
            )
            .fillna(
                "MISSING"
            )
        )

    dataframe[
        "threshold_fallback_used"
    ] = (
        dataframe[
            "threshold_fallback_used"
        ]
        .astype(
            "string"
        )
        .str.lower()
        .map(
            {
                "true": True,
                "false": False,
                "1": True,
                "0": False,
            }
        )
        .fillna(
            False
        )
        .astype(
            bool
        )
    )

    threshold_values = dataframe[
        "threshold_c"
    ].dropna().unique()

    if threshold_values.size != 1:
        raise ValueError(
            "The input series contains multiple threshold values."
        )

    if not np.isclose(
        float(
            threshold_values[0]
        ),
        ACTIVE_THRESHOLD_C,
        rtol=0.0,
        atol=1.0e-12,
    ):
        raise ValueError(
            "Input threshold differs from the active threshold.\n"
            f"Input  : {float(threshold_values[0]):.6f} °C\n"
            f"Active : {ACTIVE_THRESHOLD_C:.6f} °C"
        )

    dataframe = dataframe.sort_values(
        "date"
    ).reset_index(
        drop=True
    )

    return dataframe


# =============================================================================
# DATE AND CONTINUITY DIAGNOSTICS
# =============================================================================

def identify_duplicate_dates(
    dataframe: pd.DataFrame,
) -> pd.Series:
    """Return a Boolean mask identifying duplicate dates."""

    return dataframe["date"].duplicated(
        keep=False
    )


def identify_missing_calendar_dates(
    dataframe: pd.DataFrame,
) -> pd.DatetimeIndex:
    """Identify missing dates between the first and last observations."""

    if dataframe.empty:
        return pd.DatetimeIndex([])

    complete_range = pd.date_range(
        start=dataframe["date"].min(),
        end=dataframe["date"].max(),
        freq="D",
    )

    return complete_range.difference(
        pd.DatetimeIndex(dataframe["date"])
    )


def add_time_spacing_diagnostics(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Calculate time spacing between adjacent observations."""

    result = dataframe.copy()

    result["time_step_days"] = (
        result["date"]
        .diff()
        .dt.total_seconds()
        .div(86400.0)
    )

    result["qc_non_daily_spacing"] = (
        result["time_step_days"].notna()
        & ~np.isclose(
            result["time_step_days"],
            1.0,
            atol=1.0e-12,
        )
    )

    return result


# =============================================================================
# CIRCULAR LONGITUDE AND SPHERICAL DISTANCE
# =============================================================================

def circular_longitude_difference_deg(
    current: pd.Series,
    previous: pd.Series,
) -> np.ndarray:
    """
    Calculate signed shortest longitude difference in [-180°, 180°).
    """

    difference = (
        (
            current.to_numpy(dtype=np.float64)
            - previous.to_numpy(dtype=np.float64)
            + 180.0
        )
        % 360.0
    ) - 180.0

    return difference


def haversine_distance_km(
    lon1_deg: np.ndarray,
    lat1_deg: np.ndarray,
    lon2_deg: np.ndarray,
    lat2_deg: np.ndarray,
) -> np.ndarray:
    """
    Calculate great-circle distance using the haversine formula.
    """

    lon1_rad = np.deg2rad(lon1_deg)
    lat1_rad = np.deg2rad(lat1_deg)
    lon2_rad = np.deg2rad(lon2_deg)
    lat2_rad = np.deg2rad(lat2_deg)

    delta_lon = lon2_rad - lon1_rad
    delta_lat = lat2_rad - lat1_rad

    haversine_value = (
        np.sin(delta_lat / 2.0) ** 2
        + np.cos(lat1_rad)
        * np.cos(lat2_rad)
        * np.sin(delta_lon / 2.0) ** 2
    )

    haversine_value = np.clip(
        haversine_value,
        0.0,
        1.0,
    )

    central_angle = 2.0 * np.arcsin(
        np.sqrt(haversine_value)
    )

    return EARTH_RADIUS_KM * central_angle


# =============================================================================
# PHYSICAL AND INTERNAL CONSISTENCY CHECKS
# =============================================================================

def add_physical_range_flags(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Add physical-range and internal-consistency QC flags."""

    result = dataframe.copy()

    result["qc_lon_out_of_range"] = (
        result["lon_360"].notna()
        & ~result["lon_360"].between(
            PHYSICAL_LON_360_MIN,
            PHYSICAL_LON_360_MAX,
            inclusive="left",
        )
    )

    result["qc_lat_out_of_range"] = (
        result["lat"].notna()
        & ~result["lat"].between(
            PHYSICAL_LAT_MIN,
            PHYSICAL_LAT_MAX,
            inclusive="both",
        )
    )

    result["qc_area_out_of_range"] = (
        result["area_km2"].notna()
        & (
            (result["area_km2"] < PHYSICAL_AREA_MIN_KM2)
            | (result["area_km2"] > EARTH_SURFACE_AREA_KM2)
        )
    )

    result["qc_mean_sst_out_of_range"] = (
        result["mean_pwp_sst_c"].notna()
        & ~result["mean_pwp_sst_c"].between(
            PHYSICAL_SST_MIN_C,
            PHYSICAL_SST_MAX_C,
            inclusive="both",
        )
    )

    result["qc_max_sst_out_of_range"] = (
        result["max_pwp_sst_c"].notna()
        & ~result["max_pwp_sst_c"].between(
            PHYSICAL_SST_MIN_C,
            PHYSICAL_SST_MAX_C,
            inclusive="both",
        )
    )

    result["qc_mean_below_threshold"] = (
        result["mean_pwp_sst_c"].notna()
        & result["threshold_c"].notna()
        & (
            result["mean_pwp_sst_c"]
            < result["threshold_c"] - 1.0e-8
        )
    )

    result["qc_max_below_mean"] = (
        result["max_pwp_sst_c"].notna()
        & result["mean_pwp_sst_c"].notna()
        & (
            result["max_pwp_sst_c"]
            < result["mean_pwp_sst_c"] - 1.0e-8
        )
    )

    result["qc_cell_count_invalid"] = (
        result["pwp_cell_count"].notna()
        & result["mask_cell_count"].notna()
        & (
            (result["pwp_cell_count"] < 0)
            | (
                result["pwp_cell_count"]
                > result["mask_cell_count"]
            )
        )
    )

    result["qc_valid_ocean_count_invalid"] = (
        result["valid_ocean_cell_count"].notna()
        & result["mask_cell_count"].notna()
        & (
            (result["valid_ocean_cell_count"] < 0)
            | (
                result["valid_ocean_cell_count"]
                > result["mask_cell_count"]
            )
        )
    )

    result["qc_low_coverage"] = (
        result["ocean_data_coverage_pct"].isna()
        | (
            result["ocean_data_coverage_pct"]
            < MINIMUM_EXPECTED_COVERAGE_PCT
        )
    )

    original_flag_upper = (
        result["quality_flag"]
        .astype("string")
        .str.upper()
        .fillna("MISSING")
    )

    # LOW_COVERAGE is reassessed directly in this QC script using the
    # operational threshold appropriate for the legacy-mask/OISST pairing.
    # Other original processing flags still require review.
    result["qc_original_quality_flag"] = ~original_flag_upper.isin(
        [
            "OK",
            "LOW_COVERAGE",
        ]
    )

    lon_180_expected = (
        (
            result["lon_360"] + 180.0
        )
        % 360.0
    ) - 180.0

    result["qc_longitude_convention_mismatch"] = (
        result["lon_360"].notna()
        & result["lon_180"].notna()
        & ~np.isclose(
            result["lon_180"],
            lon_180_expected,
            atol=1.0e-6,
            rtol=0.0,
        )
    )

    result["qc_missing_core_value"] = (
        result[
            [
                "lon_360",
                "lat",
                "area_km2",
            ]
        ]
        .isna()
        .any(axis=1)
    )

    return result


# =============================================================================
# DAILY CHANGE DIAGNOSTICS
# =============================================================================

def add_daily_change_metrics(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Calculate daily changes and threshold-based diagnostic flags."""

    result = dataframe.copy()

    previous_lon = result["lon_360"].shift(1)
    previous_lat = result["lat"].shift(1)

    result["delta_lon_deg"] = circular_longitude_difference_deg(
        result["lon_360"],
        previous_lon,
    )

    result["delta_lat_deg"] = result["lat"].diff()

    result["centroid_distance_km"] = haversine_distance_km(
        lon1_deg=previous_lon.to_numpy(dtype=np.float64),
        lat1_deg=previous_lat.to_numpy(dtype=np.float64),
        lon2_deg=result["lon_360"].to_numpy(dtype=np.float64),
        lat2_deg=result["lat"].to_numpy(dtype=np.float64),
    )

    result["delta_area_km2"] = result["area_km2"].diff()

    previous_area = result["area_km2"].shift(1)

    result["area_fraction_change"] = (
        result["delta_area_km2"]
        / previous_area
    )

    result.loc[
        previous_area <= 0.0,
        "area_fraction_change",
    ] = np.nan

    result["delta_mean_pwp_sst_c"] = (
        result["mean_pwp_sst_c"].diff()
    )

    adjacent_daily = (
        result["time_step_days"].isna()
        | np.isclose(
            result["time_step_days"],
            1.0,
            atol=1.0e-12,
        )
    )

    result["qc_large_lon_change"] = (
        adjacent_daily
        & result["delta_lon_deg"].abs().gt(
            MAX_DAILY_LON_CHANGE_DEG
        )
    )

    result["qc_large_lat_change"] = (
        adjacent_daily
        & result["delta_lat_deg"].abs().gt(
            MAX_DAILY_LAT_CHANGE_DEG
        )
    )

    result["qc_large_centroid_displacement"] = (
        adjacent_daily
        & result["centroid_distance_km"].gt(
            MAX_DAILY_CENTROID_DISTANCE_KM
        )
    )

    result["qc_large_area_change"] = (
        adjacent_daily
        & result["area_fraction_change"].abs().gt(
            MAX_DAILY_AREA_FRACTION_CHANGE
        )
    )

    result["qc_large_mean_sst_change"] = (
        adjacent_daily
        & result["delta_mean_pwp_sst_c"].abs().gt(
            MAX_DAILY_MEAN_SST_CHANGE_C
        )
    )

    return result


# =============================================================================
# ROBUST ROLLING ANOMALY DETECTION
# =============================================================================

def rolling_mad(
    series: pd.Series,
    window: int,
    min_periods: int,
) -> pd.Series:
    """Calculate centred rolling median absolute deviation."""

    rolling_median = series.rolling(
        window=window,
        center=True,
        min_periods=min_periods,
    ).median()

    absolute_deviation = (
        series - rolling_median
    ).abs()

    return absolute_deviation.rolling(
        window=window,
        center=True,
        min_periods=min_periods,
    ).median()


def add_robust_anomaly_flags(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Add rolling robust-z diagnostics for key variables."""

    result = dataframe.copy()

    variables = {
        "lon": "lon_360",
        "lat": "lat",
        "area": "area_km2",
        "mean_sst": "mean_pwp_sst_c",
    }

    for short_name, column in variables.items():
        rolling_median = result[column].rolling(
            window=ROLLING_WINDOW_DAYS,
            center=True,
            min_periods=ROLLING_MIN_PERIODS,
        ).median()

        median_absolute_deviation = rolling_mad(
            series=result[column],
            window=ROLLING_WINDOW_DAYS,
            min_periods=ROLLING_MIN_PERIODS,
        )

        robust_z = (
            0.67448975
            * (
                result[column]
                - rolling_median
            )
            / median_absolute_deviation
        )

        robust_z = robust_z.replace(
            [np.inf, -np.inf],
            np.nan,
        )

        result[
            f"{short_name}_rolling_median"
        ] = rolling_median

        result[
            f"{short_name}_rolling_mad"
        ] = median_absolute_deviation

        result[
            f"{short_name}_robust_z"
        ] = robust_z

        result[
            f"qc_{short_name}_robust_outlier"
        ] = robust_z.abs().gt(
            ROBUST_Z_THRESHOLD
        )

    return result


# =============================================================================
# CONSTANT-VALUE SEQUENCE DETECTION
# =============================================================================

def constant_sequence_mask(
    series: pd.Series,
    minimum_length: int,
    tolerance: float,
) -> pd.Series:
    """
    Identify observations belonging to unusually long constant sequences.
    """

    values = pd.to_numeric(
        series,
        errors="coerce",
    )

    same_as_previous = (
        values.diff().abs() <= tolerance
    )

    groups = (
        (~same_as_previous)
        .cumsum()
    )

    group_sizes = groups.groupby(
        groups
    ).transform("size")

    return (
        values.notna()
        & group_sizes.ge(minimum_length)
    )


def add_constant_sequence_flags(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Flag extended constant sequences in major variables."""

    result = dataframe.copy()

    result["qc_constant_lon_sequence"] = (
        constant_sequence_mask(
            result["lon_360"],
            minimum_length=CONSTANT_SEQUENCE_MIN_DAYS,
            tolerance=CONSTANT_TOLERANCE,
        )
    )

    result["qc_constant_lat_sequence"] = (
        constant_sequence_mask(
            result["lat"],
            minimum_length=CONSTANT_SEQUENCE_MIN_DAYS,
            tolerance=CONSTANT_TOLERANCE,
        )
    )

    result["qc_constant_area_sequence"] = (
        constant_sequence_mask(
            result["area_km2"],
            minimum_length=CONSTANT_SEQUENCE_MIN_DAYS,
            tolerance=CONSTANT_TOLERANCE,
        )
    )

    return result


# =============================================================================
# COMPOSITE QC FLAGS
# =============================================================================

def build_composite_flags(
    dataframe: pd.DataFrame,
    duplicate_mask: pd.Series,
) -> pd.DataFrame:
    """Classify each record as PASS, CHECK, or FAIL.

    FAIL flags identify structural, physical, or data-integrity problems.
    CHECK flags identify statistically unusual or rapidly changing but
    potentially valid physical events. No observation is removed.
    """

    result = dataframe.copy()

    result["qc_duplicate_date"] = duplicate_mask.to_numpy(dtype=bool)

    fail_flags = [
        "qc_duplicate_date",
        "qc_non_daily_spacing",
        "qc_lon_out_of_range",
        "qc_lat_out_of_range",
        "qc_area_out_of_range",
        "qc_mean_sst_out_of_range",
        "qc_max_sst_out_of_range",
        "qc_mean_below_threshold",
        "qc_max_below_mean",
        "qc_cell_count_invalid",
        "qc_valid_ocean_count_invalid",
        "qc_low_coverage",
        "qc_original_quality_flag",
        "qc_longitude_convention_mismatch",
        "qc_missing_core_value",
    ]

    check_flags = [
        "qc_large_lon_change",
        "qc_large_lat_change",
        "qc_large_centroid_displacement",
        "qc_large_area_change",
        "qc_large_mean_sst_change",
        "qc_lon_robust_outlier",
        "qc_lat_robust_outlier",
        "qc_area_robust_outlier",
        "qc_mean_sst_robust_outlier",
        "qc_constant_lon_sequence",
        "qc_constant_lat_sequence",
        "qc_constant_area_sequence",
    ]

    all_flags = [
        column
        for column in fail_flags + check_flags
        if column in result.columns
    ]

    result[all_flags] = (
        result[all_flags]
        .fillna(False)
        .astype(bool)
    )

    available_fail_flags = [
        column for column in fail_flags if column in result.columns
    ]
    available_check_flags = [
        column for column in check_flags if column in result.columns
    ]

    result["qc_fail_flag_count"] = (
        result[available_fail_flags].sum(axis=1).astype(int)
        if available_fail_flags
        else 0
    )

    result["qc_check_flag_count"] = (
        result[available_check_flags].sum(axis=1).astype(int)
        if available_check_flags
        else 0
    )

    result["qc_flag_count"] = (
        result["qc_fail_flag_count"]
        + result["qc_check_flag_count"]
    )

    result["qc_status"] = np.select(
        [
            result["qc_fail_flag_count"] > 0,
            result["qc_check_flag_count"] > 0,
        ],
        [
            "FAIL",
            "CHECK",
        ],
        default="PASS",
    )

    result["qc_any_flag"] = result["qc_status"] != "PASS"

    def compile_reasons(row: pd.Series) -> str:
        active_flags = [
            column
            for column in all_flags
            if bool(row[column])
        ]
        return ";".join(active_flags)

    result["qc_reasons"] = result.apply(compile_reasons, axis=1)

    return result


# =============================================================================
# SUMMARY TABLES
# =============================================================================

def descriptive_statistics(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Create descriptive statistics for key scientific variables."""

    variables = (
        "lon_360",
        "lat",
        "area_km2",
        "pwp_cell_count",
        "ocean_data_coverage_pct",
        "mean_pwp_sst_c",
        "max_pwp_sst_c",
        "delta_lon_deg",
        "delta_lat_deg",
        "centroid_distance_km",
        "delta_area_km2",
        "area_fraction_change",
    )

    rows: list[dict[str, Any]] = []

    for variable in variables:
        series = pd.to_numeric(
            dataframe[variable],
            errors="coerce",
        )

        finite = series[
            np.isfinite(series)
        ]

        rows.append(
            {
                "variable": variable,
                "count": int(finite.size),
                "missing": int(series.isna().sum()),
                "mean": float(finite.mean())
                if not finite.empty
                else np.nan,
                "std": float(finite.std(ddof=1))
                if finite.size > 1
                else np.nan,
                "minimum": float(finite.min())
                if not finite.empty
                else np.nan,
                "q01": float(finite.quantile(0.01))
                if not finite.empty
                else np.nan,
                "q05": float(finite.quantile(0.05))
                if not finite.empty
                else np.nan,
                "median": float(finite.median())
                if not finite.empty
                else np.nan,
                "q95": float(finite.quantile(0.95))
                if not finite.empty
                else np.nan,
                "q99": float(finite.quantile(0.99))
                if not finite.empty
                else np.nan,
                "maximum": float(finite.max())
                if not finite.empty
                else np.nan,
            }
        )

    return pd.DataFrame(rows)


def build_flag_count_table(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Count all individual QC flags."""

    qc_columns = [
        column
        for column in dataframe.columns
        if column.startswith("qc_")
        and dataframe[column].dtype == bool
    ]

    rows = []

    for column in qc_columns:
        count = int(
            dataframe[column].sum()
        )

        rows.append(
            {
                "flag": column,
                "count": count,
                "percentage": (
                    100.0
                    * count
                    / len(dataframe)
                    if len(dataframe) > 0
                    else np.nan
                ),
            }
        )

    result = pd.DataFrame(rows)

    if not result.empty:
        result = result.sort_values(
            ["count", "flag"],
            ascending=[False, True],
        ).reset_index(
            drop=True
        )

    return result


def build_correlation_table(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Calculate Pearson correlations among major variables."""

    variables = [
        "lon_360",
        "lat",
        "area_km2",
        "pwp_cell_count",
        "mean_pwp_sst_c",
        "max_pwp_sst_c",
        "ocean_data_coverage_pct",
    ]

    return dataframe[variables].corr(
        method="pearson",
        min_periods=30,
    )


def build_annual_summary(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Calculate annual summary statistics."""

    working = dataframe.copy()

    working["year"] = (
        working["date"].dt.year
    )

    annual = (
        working.groupby(
            "year",
            as_index=False,
        )
        .agg(
            observation_count=(
                "date",
                "count",
            ),
            pass_count=(
                "qc_status",
                lambda values: int(
                    np.count_nonzero(
                        values == "PASS"
                    )
                ),
            ),
            check_count=(
                "qc_status",
                lambda values: int(np.count_nonzero(values == "CHECK")),
            ),
            fail_count=(
                "qc_status",
                lambda values: int(np.count_nonzero(values == "FAIL")),
            ),
            mean_lon_360=(
                "lon_360",
                "mean",
            ),
            mean_lat=(
                "lat",
                "mean",
            ),
            mean_area_km2=(
                "area_km2",
                "mean",
            ),
            median_area_km2=(
                "area_km2",
                "median",
            ),
            mean_pwp_sst_c=(
                "mean_pwp_sst_c",
                "mean",
            ),
            minimum_coverage_pct=(
                "ocean_data_coverage_pct",
                "min",
            ),
            maximum_daily_distance_km=(
                "centroid_distance_km",
                "max",
            ),
        )
    )

    annual["check_percentage"] = (
        100.0 * annual["check_count"] / annual["observation_count"]
    )
    annual["fail_percentage"] = (
        100.0 * annual["fail_count"] / annual["observation_count"]
    )

    return annual


def build_summary_table(
    dataframe: pd.DataFrame,
    missing_dates: pd.DatetimeIndex,
    duplicate_count: int,
) -> pd.DataFrame:
    """Create a compact overall QC summary."""

    start_date = dataframe["date"].min()
    end_date = dataframe["date"].max()

    expected_count = (
        (end_date - start_date).days + 1
    )

    metrics = [
        ("records", len(dataframe)),
        ("expected_calendar_days", expected_count),
        ("missing_calendar_days", len(missing_dates)),
        ("duplicate_date_records", duplicate_count),
        (
            "pass_records",
            int(
                np.count_nonzero(
                    dataframe["qc_status"] == "PASS"
                )
            ),
        ),
        (
            "review_records",
            int(
                np.count_nonzero(
                    dataframe["qc_status"].isin(["CHECK", "FAIL"])
                )
            ),
        ),
        (
            "minimum_coverage_pct",
            float(
                dataframe[
                    "ocean_data_coverage_pct"
                ].min()
            ),
        ),
        (
            "maximum_daily_centroid_distance_km",
            float(
                dataframe[
                    "centroid_distance_km"
                ].max()
            ),
        ),
        (
            "maximum_absolute_daily_lon_change_deg",
            float(
                dataframe[
                    "delta_lon_deg"
                ].abs().max()
            ),
        ),
        (
            "maximum_absolute_daily_lat_change_deg",
            float(
                dataframe[
                    "delta_lat_deg"
                ].abs().max()
            ),
        ),
        (
            "maximum_absolute_area_fraction_change",
            float(
                dataframe[
                    "area_fraction_change"
                ].abs().max()
            ),
        ),
    ]

    return pd.DataFrame(
        metrics,
        columns=[
            "metric",
            "value",
        ],
    )


# =============================================================================
# FIGURE UTILITIES
# =============================================================================

def configure_date_axis(
    axis: plt.Axes,
    dates: pd.Series,
    show_labels: bool,
) -> None:
    """
    Configure a publication-standard temporal axis.

    The x-axis is restricted exactly to the observed date interval. Major
    ticks follow the project convention of three-year intervals anchored at
    1982, and no tick or tick label is permitted outside the data limits.
    """

    date_index = pd.DatetimeIndex(
        pd.to_datetime(
            dates,
            errors="raise",
        )
    )

    minimum_date = pd.Timestamp(
        date_index.min()
    )

    maximum_date = pd.Timestamp(
        date_index.max()
    )

    start_year = int(
        minimum_date.year
    )

    end_year = int(
        maximum_date.year
    )

    first_tick_year = max(
        YEAR_TICK_ANCHOR,
        start_year,
    )

    offset = (
        first_tick_year - YEAR_TICK_ANCHOR
    ) % YEAR_TICK_INTERVAL

    if offset != 0:
        first_tick_year += (
            YEAR_TICK_INTERVAL
            - offset
        )

    candidate_years = np.arange(
        first_tick_year,
        end_year + 1,
        YEAR_TICK_INTERVAL,
        dtype=int,
    )

    candidate_dates = pd.DatetimeIndex(
        pd.to_datetime(
            [
                f"{year}-01-01"
                for year in candidate_years
            ]
        )
    )

    inside_limits = (
        (candidate_dates >= minimum_date)
        & (candidate_dates <= maximum_date)
    )

    tick_dates = candidate_dates[
        inside_limits
    ]

    tick_years = candidate_years[
        inside_limits
    ]

    axis.set_xlim(
        minimum_date,
        maximum_date,
    )

    axis.margins(
        x=0.0
    )

    axis.set_xticks(
        tick_dates
    )

    if show_labels:
        axis.set_xticklabels(
            [
                str(year)
                for year in tick_years
            ],
            rotation=0,
            ha="center",
        )

        axis.set_xlabel(
            TIME_AXIS_LABEL
        )
    else:
        axis.tick_params(
            axis="x",
            labelbottom=False,
        )

    axis.grid(
        linestyle=GRID_LINESTYLE,
        linewidth=GRID_LINEWIDTH,
        alpha=GRID_ALPHA,
    )

def add_panel_label(
    axis: plt.Axes,
    label: str,
) -> None:
    """Add the project-standard panel label."""

    axis.text(
        PANEL_LABEL_X,
        PANEL_LABEL_Y,
        label,
        transform=axis.transAxes,
        ha="left",
        va="top",
        fontsize=PANEL_LABEL_FONT_SIZE,
        fontweight=PANEL_LABEL_FONT_WEIGHT,
    )


def save_publication_figure(
    figure: plt.Figure,
    output_file: Path,
) -> None:
    """Save and close one publication-quality figure."""

    figure.savefig(
        output_file,
        dpi=FIGURE_DPI,
        bbox_inches=SAVE_BBOX,
        pad_inches=SAVE_PAD_INCHES,
        transparent=SAVE_TRANSPARENT,
    )

    plt.close(
        figure
    )


# =============================================================================
# FIGURES
# =============================================================================

def plot_daily_series(
    dataframe: pd.DataFrame,
) -> None:
    """Plot longitude, latitude, and area daily time series."""

    figure, axes = plt.subplots(
        nrows=3,
        ncols=1,
        figsize=(14, 10),
        sharex=True,
    )

    review = dataframe["qc_status"].isin(["CHECK", "FAIL"])

    axes[0].plot(
        dataframe["date"],
        dataframe["lon_360"],
        linewidth=0.7,
        label="Daily centroid",
    )

    axes[0].scatter(
        dataframe.loc[review, "date"],
        dataframe.loc[review, "lon_360"],
        s=8,
        marker="o",
        label="QC CHECK/FAIL",
        zorder=3,
    )

    axes[0].set_ylabel("Longitude (°E)")
    axes[0].legend(
        frameon=False,
        loc="upper right",
    )
    add_panel_label(
        axes[0],
        "A)",
    )

    axes[1].plot(
        dataframe["date"],
        dataframe["lat"],
        linewidth=0.7,
    )

    axes[1].scatter(
        dataframe.loc[review, "date"],
        dataframe.loc[review, "lat"],
        s=8,
        marker="o",
        zorder=3,
    )

    axes[1].set_ylabel("Latitude (°)")
    add_panel_label(
        axes[1],
        "B)",
    )

    axes[2].plot(
        dataframe["date"],
        dataframe["area_km2"] / 1.0e6,
        linewidth=0.7,
    )

    axes[2].scatter(
        dataframe.loc[review, "date"],
        dataframe.loc[review, "area_km2"] / 1.0e6,
        s=8,
        marker="o",
        zorder=3,
    )

    axes[2].set_ylabel("Area (10⁶ km²)")
    add_panel_label(
        axes[2],
        "C)",
    )

    for index, axis in enumerate(axes):
        configure_date_axis(
            axis=axis,
            dates=dataframe["date"],
            show_labels=index == len(axes) - 1,
        )

    figure.suptitle(
        "Daily Pacific Warm Pool centroid and area with QC review records",
        y=0.995,
    )

    figure.tight_layout()

    save_publication_figure(
        figure=figure,
        output_file=FIGURE_DAILY_SERIES,
    )


def plot_daily_changes(
    dataframe: pd.DataFrame,
) -> None:
    """Plot daily centroid movement and area change."""

    figure, axes = plt.subplots(
        nrows=3,
        ncols=1,
        figsize=(14, 10),
        sharex=True,
    )

    axes[0].plot(
        dataframe["date"],
        dataframe["delta_lon_deg"],
        linewidth=0.7,
    )

    axes[0].axhline(
        MAX_DAILY_LON_CHANGE_DEG,
        linestyle="--",
        linewidth=1.0,
    )

    axes[0].axhline(
        -MAX_DAILY_LON_CHANGE_DEG,
        linestyle="--",
        linewidth=1.0,
    )

    axes[0].set_ylabel("Δ longitude (° day⁻¹)")
    add_panel_label(
        axes[0],
        "A)",
    )

    axes[1].plot(
        dataframe["date"],
        dataframe["centroid_distance_km"],
        linewidth=0.7,
    )

    axes[1].axhline(
        MAX_DAILY_CENTROID_DISTANCE_KM,
        linestyle="--",
        linewidth=1.0,
    )

    axes[1].set_ylabel("Distance (km day⁻¹)")
    add_panel_label(
        axes[1],
        "B)",
    )

    axes[2].plot(
        dataframe["date"],
        dataframe["area_fraction_change"] * 100.0,
        linewidth=0.7,
    )

    axes[2].axhline(
        100.0 * MAX_DAILY_AREA_FRACTION_CHANGE,
        linestyle="--",
        linewidth=1.0,
    )

    axes[2].axhline(
        -100.0 * MAX_DAILY_AREA_FRACTION_CHANGE,
        linestyle="--",
        linewidth=1.0,
    )

    axes[2].set_ylabel("Area change (% day⁻¹)")
    add_panel_label(
        axes[2],
        "C)",
    )

    for index, axis in enumerate(axes):
        configure_date_axis(
            axis=axis,
            dates=dataframe["date"],
            show_labels=index == len(axes) - 1,
        )

    figure.suptitle(
        "Daily changes in Pacific Warm Pool geometry",
        y=0.995,
    )

    figure.tight_layout()

    save_publication_figure(
        figure=figure,
        output_file=FIGURE_DAILY_CHANGES,
    )


def plot_distributions(
    dataframe: pd.DataFrame,
) -> None:
    """Plot distributions of major PWP variables."""

    figure, axes = plt.subplots(
        nrows=2,
        ncols=2,
        figsize=(13, 9),
    )

    panels = (
        (
            "lon_360",
            "Centroid longitude (°E)",
            "A)",
        ),
        (
            "lat",
            "Centroid latitude (°)",
            "B)",
        ),
        (
            "area_km2",
            "PWP area (km²)",
            "C)",
        ),
        (
            "mean_pwp_sst_c",
            "Area-weighted mean SST (°C)",
            "D)",
        ),
    )

    for axis, (
        column,
        xlabel,
        panel_label,
    ) in zip(
        axes.ravel(),
        panels,
    ):
        values = dataframe[column].dropna()

        axis.hist(
            values,
            bins=50,
        )

        axis.axvline(
            values.median(),
            linestyle="--",
            linewidth=1.2,
            label="Median",
        )

        axis.set_xlabel(
            xlabel
        )

        axis.set_ylabel(
            "Frequency"
        )

        axis.grid(
            linestyle=":",
            linewidth=0.6,
            alpha=0.5,
        )

        axis.legend(
            frameon=False,
        )

        add_panel_label(
            axis,
            panel_label,
        )

    figure.suptitle(
        "Distributions of daily Pacific Warm Pool diagnostics",
        y=0.995,
    )

    figure.tight_layout()

    save_publication_figure(
        figure=figure,
        output_file=FIGURE_DISTRIBUTIONS,
    )


def plot_coverage_and_flags(
    dataframe: pd.DataFrame,
    flag_counts: pd.DataFrame,
) -> None:
    """Plot daily coverage and most frequent QC flags."""

    figure, axes = plt.subplots(
        nrows=2,
        ncols=1,
        figsize=(14, 9),
    )

    axes[0].plot(
        dataframe["date"],
        dataframe["ocean_data_coverage_pct"],
        linewidth=0.7,
    )

    axes[0].axhline(
        MINIMUM_EXPECTED_COVERAGE_PCT,
        linestyle="--",
        linewidth=1.0,
        label="Minimum expected coverage",
    )

    axes[0].set_ylabel("Coverage (%)")
    axes[0].legend(
        frameon=False,
        loc="lower right",
    )

    configure_date_axis(
        axis=axes[0],
        dates=dataframe["date"],
        show_labels=True,
    )

    add_panel_label(
        axes[0],
        "A)",
    )

    nonzero_flags = flag_counts.loc[
        flag_counts["count"] > 0
    ].head(15)

    axes[1].barh(
        nonzero_flags["flag"],
        nonzero_flags["count"],
    )

    axes[1].invert_yaxis()
    axes[1].set_xlabel("Flagged records")
    axes[1].set_ylabel("QC flag")
    axes[1].grid(
        axis="x",
        linestyle=":",
        linewidth=0.6,
        alpha=0.5,
    )

    add_panel_label(
        axes[1],
        "B)",
    )

    figure.suptitle(
        "OISST coverage and quality-control flags",
        y=0.995,
    )

    figure.tight_layout()

    save_publication_figure(
        figure=figure,
        output_file=FIGURE_COVERAGE_FLAGS,
    )


def plot_annual_summary(
    annual_summary: pd.DataFrame,
) -> None:
    """Plot annual mean longitude, latitude, and area."""

    figure, axes = plt.subplots(
        nrows=3,
        ncols=1,
        figsize=(14, 10),
        sharex=True,
    )

    axes[0].plot(
        annual_summary["year"],
        annual_summary["mean_lon_360"],
        marker="o",
        linewidth=1.0,
    )

    axes[0].set_ylabel("Mean longitude (°E)")
    add_panel_label(
        axes[0],
        "A)",
    )

    axes[1].plot(
        annual_summary["year"],
        annual_summary["mean_lat"],
        marker="o",
        linewidth=1.0,
    )

    axes[1].set_ylabel("Mean latitude (°)")
    add_panel_label(
        axes[1],
        "B)",
    )

    axes[2].plot(
        annual_summary["year"],
        annual_summary["mean_area_km2"] / 1.0e6,
        marker="o",
        linewidth=1.0,
    )

    axes[2].set_ylabel("Mean area (10⁶ km²)")
    axes[2].set_xlabel("Year")
    add_panel_label(
        axes[2],
        "C)",
    )

    tick_years = np.arange(
        max(
            1982,
            int(annual_summary["year"].min()),
        ),
        int(annual_summary["year"].max()) + 1,
        YEAR_TICK_INTERVAL,
    )

    axes[2].set_xticks(
        tick_years
    )

    for axis in axes:
        axis.grid(
            linestyle=":",
            linewidth=0.6,
            alpha=0.5,
        )

    figure.suptitle(
        "Annual summary of Pacific Warm Pool geometry",
        y=0.995,
    )

    figure.tight_layout()

    save_publication_figure(
        figure=figure,
        output_file=FIGURE_ANNUAL_SUMMARY,
    )


# =============================================================================
# EXPORTS
# =============================================================================

def export_qc_series(
    dataframe: pd.DataFrame,
) -> None:
    """Export the complete daily series with QC diagnostics."""

    output = dataframe.copy()

    output["date"] = (
        output["date"]
        .dt.strftime("%Y-%m-%d")
    )

    output.to_csv(
        OUTPUT_QC_CSV,
        index=False,
        encoding="utf-8",
        float_format="%.8f",
        lineterminator="\n",
    )


def export_tables(
    dataframe: pd.DataFrame,
    missing_dates: pd.DatetimeIndex,
    summary: pd.DataFrame,
    flag_counts: pd.DataFrame,
    descriptive: pd.DataFrame,
    correlations: pd.DataFrame,
    annual_summary: pd.DataFrame,
) -> None:
    """Export all diagnostic tables."""

    summary.to_csv(
        SUMMARY_TABLE,
        index=False,
        float_format="%.8f",
    )

    flag_counts.to_csv(
        FLAG_COUNT_TABLE,
        index=False,
        float_format="%.8f",
    )

    pd.DataFrame(
        {
            "missing_date": missing_dates.strftime(
                "%Y-%m-%d"
            )
        }
    ).to_csv(
        MISSING_DATES_TABLE,
        index=False,
    )

    suspect_columns = [
        "date",
        "lon_360",
        "lat",
        "area_km2",
        "mean_pwp_sst_c",
        "ocean_data_coverage_pct",
        "quality_flag",
        "qc_status",
        "qc_fail_flag_count",
        "qc_check_flag_count",
        "qc_flag_count",
        "qc_reasons",
        "source_file",
    ]

    suspect_records = dataframe.loc[
        dataframe["qc_status"].isin(["CHECK", "FAIL"]),
        suspect_columns,
    ].copy()

    suspect_records["date"] = (
        suspect_records["date"]
        .dt.strftime("%Y-%m-%d")
    )

    suspect_records.to_csv(
        SUSPECT_RECORDS_TABLE,
        index=False,
        float_format="%.8f",
    )

    descriptive.to_csv(
        DESCRIPTIVE_TABLE,
        index=False,
        float_format="%.8f",
    )

    correlations.to_csv(
        CORRELATION_TABLE,
        index=True,
        float_format="%.8f",
    )

    annual_summary.to_csv(
        ANNUAL_SUMMARY_TABLE,
        index=False,
        float_format="%.8f",
    )


# =============================================================================
# REPORT
# =============================================================================

def write_report(
    dataframe: pd.DataFrame,
    missing_dates: pd.DatetimeIndex,
    duplicate_count: int,
    flag_counts: pd.DataFrame,
    input_checksum: str,
) -> None:
    """Write the complete scientific QC report."""

    generated_utc = datetime.now(
        timezone.utc
    ).isoformat()

    pass_count = int(
        np.count_nonzero(
            dataframe["qc_status"] == "PASS"
        )
    )

    check_count = int(
        np.count_nonzero(
            dataframe["qc_status"] == "CHECK"
        )
    )

    fail_count = int(
        np.count_nonzero(
            dataframe["qc_status"] == "FAIL"
        )
    )

    highest_flags = flag_counts.loc[
        flag_counts["count"] > 0
    ].head(20)

    lines = [
        "PACIFIC WARM POOL TIME-SERIES QUALITY-CONTROL REPORT",
        "=" * 78,
        "",
        "1. PROCESSING INFORMATION",
        "-" * 78,
        f"Generated UTC                   : {generated_utc}",
        f"Program version                 : {PROGRAM_VERSION}",
        f"Script                          : {SCRIPT_FILE}",
        f"Pipeline module                 : quality_control",
        f"Threshold                       : {ACTIVE_THRESHOLD_C:.3f} °C",
        f"Threshold folder                : {ACTIVE_THRESHOLD_FOLDER}",
        f"Centroid input file             : {INPUT_CSV}",
        f"QC processed directory          : {OUTPUT_QC_CSV.parent}",
        f"QC table directory              : {TABLE_DIR}",
        f"QC figure directory             : {FIGURE_DIR}",
        f"QC report directory             : {REPORT_DIR}",
        f"Input SHA-256                   : {input_checksum}",
        f"QC output file                  : {OUTPUT_QC_CSV}",
        "",
        "2. TEMPORAL COVERAGE",
        "-" * 78,
        f"First observation               : {dataframe['date'].min():%Y-%m-%d}",
        f"Last observation                : {dataframe['date'].max():%Y-%m-%d}",
        f"Number of records               : {len(dataframe):,}",
        f"Duplicate-date records          : {duplicate_count:,}",
        f"Missing calendar dates          : {len(missing_dates):,}",
        "",
        "3. RECORD-LEVEL QC RESULTS",
        "-" * 78,
        f"PASS records                    : {pass_count:,}",
        f"CHECK records                   : {check_count:,}",
        f"FAIL records                    : {fail_count:,}",
        (
            "CHECK percentage               : "
            f"{100.0 * check_count / len(dataframe):.6f}%"
        ),
        "",
        "4. CONFIGURED DIAGNOSTIC LIMITS",
        "-" * 78,
        (
            "Minimum daily coverage          : "
            f"{MINIMUM_EXPECTED_COVERAGE_PCT:.3f}%"
        ),
        (
            "Maximum daily longitude change  : "
            f"{MAX_DAILY_LON_CHANGE_DEG:.3f}°"
        ),
        (
            "Maximum daily latitude change   : "
            f"{MAX_DAILY_LAT_CHANGE_DEG:.3f}°"
        ),
        (
            "Maximum centroid displacement   : "
            f"{MAX_DAILY_CENTROID_DISTANCE_KM:.3f} km"
        ),
        (
            "Maximum daily area fraction     : "
            f"{MAX_DAILY_AREA_FRACTION_CHANGE:.3f}"
        ),
        (
            "Maximum daily mean-SST change   : "
            f"{MAX_DAILY_MEAN_SST_CHANGE_C:.3f} °C"
        ),
        (
            "Rolling robust window           : "
            f"{ROLLING_WINDOW_DAYS} days"
        ),
        (
            "Rolling minimum observations    : "
            f"{ROLLING_MIN_PERIODS}"
        ),
        (
            "Robust-z review threshold       : "
            f"{ROBUST_Z_THRESHOLD:.3f}"
        ),
        "",
        "5. DATA EXTREMES",
        "-" * 78,
        (
            "Longitude range                 : "
            f"{dataframe['lon_360'].min():.6f} to "
            f"{dataframe['lon_360'].max():.6f}°E"
        ),
        (
            "Latitude range                  : "
            f"{dataframe['lat'].min():.6f} to "
            f"{dataframe['lat'].max():.6f}°"
        ),
        (
            "PWP area range                  : "
            f"{dataframe['area_km2'].min():,.3f} to "
            f"{dataframe['area_km2'].max():,.3f} km²"
        ),
        (
            "Daily centroid distance maximum : "
            f"{dataframe['centroid_distance_km'].max():,.3f} km"
        ),
        (
            "Minimum OISST coverage          : "
            f"{dataframe['ocean_data_coverage_pct'].min():.6f}%"
        ),
        "",
        "6. NONZERO QUALITY-CONTROL FLAGS",
        "-" * 78,
    ]

    if highest_flags.empty:
        lines.append(
            "No nonzero QC flags were detected."
        )
    else:
        for _, row in highest_flags.iterrows():
            lines.append(
                f"{row['flag']:<42}: "
                f"{int(row['count']):>8,} "
                f"({row['percentage']:.6f}%)"
            )

    lines.extend(
        [
            "",
            "7. INTERPRETATION",
            "-" * 78,
            (
                "A CHECK classification indicates that one or more "
                "diagnostic criteria were met. It does not automatically "
                "mean that the observation is erroneous."
            ),
            (
                "Extreme values may represent physically meaningful PWP "
                "responses during major ENSO events. Each CHECK record "
                "must therefore be evaluated together with the original "
                "OISST field, processing coverage, and surrounding dates."
            ),
            (
                "No automatic interpolation, smoothing, deletion, clipping, "
                "or replacement was applied to the scientific variables."
            ),
            (
                "The QC-enhanced output preserves the original observations "
                "and provides explicit flags for reproducible downstream "
                "decisions."
            ),
            "",
            "8. OUTPUT FILES",
            "-" * 78,
            str(OUTPUT_QC_CSV),
            str(SUMMARY_TABLE),
            str(FLAG_COUNT_TABLE),
            str(MISSING_DATES_TABLE),
            str(SUSPECT_RECORDS_TABLE),
            str(DESCRIPTIVE_TABLE),
            str(CORRELATION_TABLE),
            str(ANNUAL_SUMMARY_TABLE),
            str(FIGURE_DAILY_SERIES),
            str(FIGURE_DAILY_CHANGES),
            str(FIGURE_DISTRIBUTIONS),
            str(FIGURE_COVERAGE_FLAGS),
            str(FIGURE_ANNUAL_SUMMARY),
            "",
            "=" * 78,
            "END OF REPORT",
            "=" * 78,
        ]
    )

    REPORT_FILE.write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )
def build_threshold_comparison_summary(
    results: dict[
        float,
        pd.DataFrame,
    ],
) -> pd.DataFrame:
    """Build QC statistics across all processed thresholds."""

    records: list[
        dict[str, Any]
    ] = []

    for threshold_c, dataframe in sorted(
        results.items()
    ):
        status_counts = dataframe[
            "qc_status"
        ].value_counts()

        records.append(
            {
                "threshold_c": threshold_c,
                "threshold_folder": threshold_folder_name(
                    threshold_c
                ),
                "records": len(
                    dataframe
                ),
                "start_date": dataframe[
                    "date"
                ].min().strftime(
                    "%Y-%m-%d"
                ),
                "end_date": dataframe[
                    "date"
                ].max().strftime(
                    "%Y-%m-%d"
                ),
                "pass_records": int(
                    status_counts.get(
                        "PASS",
                        0,
                    )
                ),
                "check_records": int(
                    status_counts.get(
                        "CHECK",
                        0,
                    )
                ),
                "fail_records": int(
                    status_counts.get(
                        "FAIL",
                        0,
                    )
                ),
                "check_percentage": float(
                    100.0
                    * status_counts.get(
                        "CHECK",
                        0,
                    )
                    / len(
                        dataframe
                    )
                ),
                "fail_percentage": float(
                    100.0
                    * status_counts.get(
                        "FAIL",
                        0,
                    )
                    / len(
                        dataframe
                    )
                ),
                "minimum_coverage_pct": float(
                    dataframe[
                        "ocean_data_coverage_pct"
                    ].min()
                ),
                "maximum_daily_distance_km": float(
                    dataframe[
                        "centroid_distance_km"
                    ].max()
                ),
                "maximum_absolute_longitude_change_deg": float(
                    dataframe[
                        "delta_lon_deg"
                    ].abs().max()
                ),
                "maximum_absolute_latitude_change_deg": float(
                    dataframe[
                        "delta_lat_deg"
                    ].abs().max()
                ),
                "maximum_absolute_area_fraction_change": float(
                    dataframe[
                        "area_fraction_change"
                    ].abs().max()
                ),
            }
        )

    return pd.DataFrame(
        records
    ).sort_values(
        "threshold_c"
    ).reset_index(
        drop=True
    )


def plot_threshold_comparison(
    comparison: pd.DataFrame,
) -> None:
    """Plot PASS, CHECK, and FAIL counts across thresholds."""

    figure, axis = plt.subplots(
        figsize=(
            10,
            6,
        )
    )

    x_positions = np.arange(
        len(
            comparison
        )
    )

    width = 0.24

    axis.bar(
        x_positions - width,
        comparison[
            "pass_records"
        ],
        width=width,
        label="PASS",
    )

    axis.bar(
        x_positions,
        comparison[
            "check_records"
        ],
        width=width,
        label="CHECK",
    )

    axis.bar(
        x_positions + width,
        comparison[
            "fail_records"
        ],
        width=width,
        label="FAIL",
    )

    axis.set_xticks(
        x_positions
    )

    axis.set_xticklabels(
        [
            f"{value:g} °C"
            for value in comparison[
                "threshold_c"
            ]
        ]
    )

    axis.set_xlabel(
        "PWP SST threshold"
    )

    axis.set_ylabel(
        "Number of daily records"
    )

    axis.set_title(
        "Quality-control classification by PWP threshold"
    )

    axis.grid(
        axis="y",
        linestyle=GRID_LINESTYLE,
        linewidth=GRID_LINEWIDTH,
        alpha=GRID_ALPHA,
    )

    axis.legend(
        frameon=False,
    )

    save_publication_figure(
        figure=figure,
        output_file=COMPARISON_FIGURE,
    )


def export_threshold_comparison(
    results: dict[
        float,
        pd.DataFrame,
    ],
) -> tuple[
    Path,
    Path,
    Path,
] | None:
    """Export cross-threshold QC products."""

    if len(
        results
    ) <= 1:
        return None

    comparison = build_threshold_comparison_summary(
        results
    )

    comparison.to_csv(
        COMPARISON_SUMMARY_TABLE,
        index=False,
        encoding="utf-8",
        float_format="%.8f",
        lineterminator="\n",
    )

    plot_threshold_comparison(
        comparison
    )

    lines = [
        "PACIFIC WARM POOL QUALITY-CONTROL THRESHOLD COMPARISON",
        "=" * 78,
        "",
        f"Generated UTC              : {datetime.now(timezone.utc).isoformat()}",
        "",
        "SUMMARY",
        "-" * 78,
    ]

    for record in comparison.to_dict(
        orient="records"
    ):
        lines.extend(
            [
                f"Threshold                  : {record['threshold_c']:.1f} °C",
                f"Folder                     : {record['threshold_folder']}",
                f"Records                    : {record['records']:,}",
                f"PASS                       : {record['pass_records']:,}",
                f"CHECK                      : {record['check_records']:,}",
                f"FAIL                       : {record['fail_records']:,}",
                f"Minimum coverage           : {record['minimum_coverage_pct']:.6f}%",
                (
                    "Maximum daily distance     : "
                    f"{record['maximum_daily_distance_km']:,.6f} km"
                ),
                "",
            ]
        )

    lines.extend(
        [
            "FILES",
            "-" * 78,
            str(
                COMPARISON_SUMMARY_TABLE
            ),
            str(
                COMPARISON_FIGURE
            ),
            str(
                COMPARISON_REPORT
            ),
            "",
            "STATUS",
            "-" * 78,
            "Status                     : SUCCESS",
            "",
            "=" * 78,
            "END OF REPORT",
            "=" * 78,
        ]
    )

    COMPARISON_REPORT.write_text(
        "\n".join(
            lines
        )
        + "\n",
        encoding="utf-8",
    )

    return (
        COMPARISON_SUMMARY_TABLE,
        COMPARISON_FIGURE,
        COMPARISON_REPORT,
    )




# =============================================================================
# MAIN
# =============================================================================

def process_one_threshold(
    context: ThresholdContext,
) -> tuple[
    pd.DataFrame,
    tuple[
        Path,
        ...,
    ],
]:
    """Execute the complete quality-control workflow for one threshold."""

    activate_context(
        context
    )

    ensure_output_directories()

    input_checksum = calculate_sha256(
        INPUT_CSV
    )

    dataframe = load_input_series()

    duplicate_mask = identify_duplicate_dates(
        dataframe
    )

    duplicate_count = int(
        duplicate_mask.sum()
    )

    missing_dates = identify_missing_calendar_dates(
        dataframe
    )

    print_section(
        f"INPUT SERIES — {context.threshold_c:.1f} °C"
    )

    print(
        f"Centroid input file       : {INPUT_CSV}"
    )

    print(
        f"Quality-control output    : {OUTPUT_QC_CSV}"
    )

    print(
        f"QC table directory        : {TABLE_DIR}"
    )

    print(
        f"QC figure directory       : {FIGURE_DIR}"
    )

    print(
        f"QC report directory       : {REPORT_DIR}"
    )

    print(
        f"Records                   : {len(dataframe):,}"
    )

    print(
        f"Start date                : {dataframe['date'].min():%Y-%m-%d}"
    )

    print(
        f"End date                  : {dataframe['date'].max():%Y-%m-%d}"
    )

    print(
        f"Duplicate-date records    : {duplicate_count:,}"
    )

    print(
        f"Missing calendar dates    : {len(missing_dates):,}"
    )

    dataframe = add_time_spacing_diagnostics(
        dataframe
    )

    dataframe = add_physical_range_flags(
        dataframe
    )

    dataframe = add_daily_change_metrics(
        dataframe
    )

    dataframe = add_robust_anomaly_flags(
        dataframe
    )

    dataframe = add_constant_sequence_flags(
        dataframe
    )

    dataframe = build_composite_flags(
        dataframe=dataframe,
        duplicate_mask=duplicate_mask,
    )

    descriptive = descriptive_statistics(
        dataframe
    )

    flag_counts = build_flag_count_table(
        dataframe
    )

    correlations = build_correlation_table(
        dataframe
    )

    annual_summary = build_annual_summary(
        dataframe
    )

    summary = build_summary_table(
        dataframe=dataframe,
        missing_dates=missing_dates,
        duplicate_count=duplicate_count,
    )

    export_qc_series(
        dataframe
    )

    export_tables(
        dataframe=dataframe,
        missing_dates=missing_dates,
        summary=summary,
        flag_counts=flag_counts,
        descriptive=descriptive,
        correlations=correlations,
        annual_summary=annual_summary,
    )

    plot_daily_series(
        dataframe
    )

    plot_daily_changes(
        dataframe
    )

    plot_distributions(
        dataframe
    )

    plot_coverage_and_flags(
        dataframe=dataframe,
        flag_counts=flag_counts,
    )

    plot_annual_summary(
        annual_summary
    )

    write_report(
        dataframe=dataframe,
        missing_dates=missing_dates,
        duplicate_count=duplicate_count,
        flag_counts=flag_counts,
        input_checksum=input_checksum,
    )

    pass_count = int(
        np.count_nonzero(
            dataframe[
                "qc_status"
            ]
            == "PASS"
        )
    )

    check_count = int(
        np.count_nonzero(
            dataframe[
                "qc_status"
            ]
            == "CHECK"
        )
    )

    fail_count = int(
        np.count_nonzero(
            dataframe[
                "qc_status"
            ]
            == "FAIL"
        )
    )

    print_section(
        f"QUALITY-CONTROL SUMMARY — {context.threshold_c:.1f} °C"
    )

    print(
        f"PASS records              : {pass_count:,}"
    )

    print(
        f"CHECK records             : {check_count:,}"
    )

    print(
        f"FAIL records              : {fail_count:,}"
    )

    print(
        f"CHECK percentage          : "
        f"{100.0 * check_count / len(dataframe):.4f}%"
    )

    print(
        f"Minimum coverage          : "
        f"{dataframe['ocean_data_coverage_pct'].min():.4f}%"
    )

    print(
        f"Maximum daily distance    : "
        f"{dataframe['centroid_distance_km'].max():,.2f} km"
    )

    print(
        f"Maximum |Δ longitude|     : "
        f"{dataframe['delta_lon_deg'].abs().max():.4f}°"
    )

    print(
        f"Maximum |Δ latitude|      : "
        f"{dataframe['delta_lat_deg'].abs().max():.4f}°"
    )

    print(
        f"Missing calendar dates    : {len(missing_dates):,}"
    )

    created_files = (
        OUTPUT_QC_CSV,
        SUMMARY_TABLE,
        FLAG_COUNT_TABLE,
        MISSING_DATES_TABLE,
        SUSPECT_RECORDS_TABLE,
        DESCRIPTIVE_TABLE,
        CORRELATION_TABLE,
        ANNUAL_SUMMARY_TABLE,
        FIGURE_DAILY_SERIES,
        FIGURE_DAILY_CHANGES,
        FIGURE_DISTRIBUTIONS,
        FIGURE_COVERAGE_FLAGS,
        FIGURE_ANNUAL_SUMMARY,
        REPORT_FILE,
    )

    return (
        dataframe,
        created_files,
    )


def main() -> None:
    """Execute quality control for all configured PWP thresholds."""

    print_header(
        PROGRAM_NAME
    )

    contexts = selected_threshold_contexts()

    validate_configuration_and_directories(
        contexts
    )

    print_section(
        "CONFIGURATION"
    )

    print(
        f"Program version           : {PROGRAM_VERSION}"
    )

    print(
        f"Project root              : {PROJECT_DIR}"
    )

    print(
        f"Script                    : {SCRIPT_FILE}"
    )

    print(
        f"Execution mode            : "
        f"{'all thresholds' if RUN_ALL_THRESHOLDS else 'single threshold'}"
    )

    print(
        "Thresholds selected       : "
        + ", ".join(
            f"{context.threshold_c:.1f} °C"
            for context in contexts
        )
    )

    results: dict[
        float,
        pd.DataFrame,
    ] = {}

    created_files: list[
        Path
    ] = []

    for context in contexts:
        dataframe, threshold_files = process_one_threshold(
            context
        )

        results[
            context.threshold_c
        ] = dataframe

        created_files.extend(
            threshold_files
        )

    comparison_files = export_threshold_comparison(
        results
    )

    if comparison_files is not None:
        created_files.extend(
            comparison_files
        )

    print_section(
        "FILES CREATED"
    )

    for file_path in created_files:
        print(
            file_path
        )

    print()

    print(
        "=" * 78
    )

    print(
        "PROGRAM 06 COMPLETED SUCCESSFULLY."
    )

    print(
        "Quality-control products were generated for: "
        + ", ".join(
            f"{context.threshold_c:.1f} °C"
            for context in contexts
        )
    )

    print(
        "Centroid inputs were read from the centroid module and all outputs "
        "were stored in the quality_control module."
    )

    print(
        "=" * 78
    )


if __name__ == "__main__":
    main()  